# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train_file_bundle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='train_file_bundle.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17train_file_bundle.proto\"9\n\tTrainFile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\r\n\x05index\x18\x03 \x01(\x05\"1\n\x0fTrainFileBundle\x12\x1e\n\ntrainFiles\x18\x01 \x03(\x0b\x32\n.TrainFileb\x06proto3'
)




_TRAINFILE = _descriptor.Descriptor(
  name='TrainFile',
  full_name='TrainFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TrainFile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='TrainFile.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='TrainFile.index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=84,
)


_TRAINFILEBUNDLE = _descriptor.Descriptor(
  name='TrainFileBundle',
  full_name='TrainFileBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainFiles', full_name='TrainFileBundle.trainFiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=135,
)

_TRAINFILEBUNDLE.fields_by_name['trainFiles'].message_type = _TRAINFILE
DESCRIPTOR.message_types_by_name['TrainFile'] = _TRAINFILE
DESCRIPTOR.message_types_by_name['TrainFileBundle'] = _TRAINFILEBUNDLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainFile = _reflection.GeneratedProtocolMessageType('TrainFile', (_message.Message,), {
  'DESCRIPTOR' : _TRAINFILE,
  '__module__' : 'train_file_bundle_pb2'
  # @@protoc_insertion_point(class_scope:TrainFile)
  })
_sym_db.RegisterMessage(TrainFile)

TrainFileBundle = _reflection.GeneratedProtocolMessageType('TrainFileBundle', (_message.Message,), {
  'DESCRIPTOR' : _TRAINFILEBUNDLE,
  '__module__' : 'train_file_bundle_pb2'
  # @@protoc_insertion_point(class_scope:TrainFileBundle)
  })
_sym_db.RegisterMessage(TrainFileBundle)


# @@protoc_insertion_point(module_scope)
